/* eslint-disable import-x/no-nodejs-modules */
void (async () => {
  const fs = await import('node:fs');
  const path = await import('node:path');
  const index = fs.readFileSync('src/preset-manager/index.ts', 'utf8');
  const webpackConfig = fs.existsSync('webpack.config.ts') ? fs.readFileSync('webpack.config.ts', 'utf8') : '';

  function expectIncludes(content, expected) {
    if (!content.includes(expected)) {
      throw new Error(`Expected source to include: ${expected}`);
    }
  }

  function expectNotIncludes(content, unexpected) {
    if (content.includes(unexpected)) {
      throw new Error(`Expected source not to include: ${unexpected}`);
    }
  }

  expectIncludes(index, 'const CODE_INSPECTOR_STATE_EVENT');
  expectIncludes(index, 'declare const __PRESET_MANAGER_SOURCE_LINES__');
  expectIncludes(index, "from './utils/codeInspectorSource'");
  expectIncludes(index, 'function bindCodeInspectorControls(iframeDoc: Document, parentDoc: Document)');
  expectIncludes(index, 'const codeInspectorControls = bindCodeInspectorControls(iframeDoc, window.parent.document);');
  expectIncludes(index, "nextApp.provide('presetManagerCodeInspector', codeInspectorControls);");
  expectIncludes(index, 'type InspectorLocateTarget =');
  expectIncludes(index, 'function requestCodeInspectorLocate(iframeDoc: Document, sourceInfo: InspectorSourceInfo, target: InspectorLocateTarget = {})');
  expectIncludes(index, 'function cleanupCodeInspectorArtifacts(doc: Document | null | undefined)');
  expectIncludes(index, 'data-preset-manager-code-inspector-cleanup');
  expectIncludes(index, 'code-inspector-component,');
  expectIncludes(index, '.inspector-switch,');
  expectIncludes(index, '#inspector-node-tree,');
  expectIncludes(index, '.code-inspector-notification');
  expectIncludes(index, "doc?.querySelectorAll('code-inspector-component').forEach(element => element.remove());");
  expectIncludes(index, "doc?.getElementById('code-inspector-notification-styles')?.remove();");
  expectIncludes(index, 'cleanupCodeInspectorArtifacts(window.document);');
  expectIncludes(index, 'cleanupCodeInspectorArtifacts(window.parent.document);');
  expectIncludes(index, 'cleanupCodeInspectorArtifacts(iframeDoc);');
  expectNotIncludes(index, 'type CodeInspectorElement = HTMLElement &');
  expectNotIncludes(index, 'injectCodeInspectorClient(iframeDoc);');
  expectNotIncludes(index, "iframeDoc.createElement('code-inspector-component')");
  expectNotIncludes(index, 'activeInspector.open = true;');
  expectNotIncludes(index, 'inspector.open = false;');
  expectNotIncludes(index, 'mountCodeInspectorInIframe(iframeDoc);');
  expectNotIncludes(index, 'bindAltShiftInspectorToggle(iframeDoc, window.parent.document);');
  expectIncludes(index, "parentDoc.addEventListener('keydown', onKeyDown, true)");
  expectIncludes(index, "parentDoc.removeEventListener('keydown', onKeyDown, true)");
  expectNotIncludes(index, 'INSPECTOR_HOLD_HOTKEYS_DISABLED');
  expectNotIncludes(index, 'hotKeys: INSPECTOR_HOLD_HOTKEYS_DISABLED');
  expectIncludes(index, "addEventListener('mousemove', onMouseMove, true)");
  expectIncludes(index, "removeEventListener('mousemove', onMouseMove, true)");
  expectIncludes(index, "addEventListener('click', onClick, true)");
  expectIncludes(index, "removeEventListener('click', onClick, true)");
  expectIncludes(index, 'data-preset-manager-inspector-overlay');
  expectIncludes(index, 'function createInspectorOverlay(iframeDoc: Document)');
  expectIncludes(index, 'iframeDoc.body.append(overlay.box, overlay.label)');
  expectIncludes(index, "overflow: 'visible'");
  expectIncludes(index, "border: '1px solid rgba(93, 188, 255, 0.56)'");
  expectIncludes(index, "background: 'rgba(93, 188, 255, 0.025)'");
  expectIncludes(index, 'pm-inspector-token-tag');
  expectIncludes(index, 'pm-inspector-token-attr');
  expectIncludes(index, 'pm-inspector-token-string');
  expectIncludes(index, 'pm-inspector-line-number');
  expectIncludes(index, 'pm-inspector-source-path');
  expectIncludes(index, 'function hideInspectorOverlay(overlay: InspectorOverlay | null)');
  expectIncludes(index, 'function removeInspectorOverlay(overlay: InspectorOverlay | null)');
  expectIncludes(index, 'function findInspectableElement(iframeDoc: Document, event: MouseEvent)');
  expectIncludes(index, 'function resolveInspectorSourceHint(element: HTMLElement, hasSourceMarker = false)');
  expectIncludes(index, 'function findInspectorSourceFromElementSignature(element: HTMLElement): InspectorSourceInfo');
  expectIncludes(index, 'function getInspectorSourceInfo(element: HTMLElement): InspectorSourceInfo');
  expectIncludes(index, 'return sourceInfo.path ? sourceInfo : findInspectorSourceFromElementSignature(element);');
  expectIncludes(index, 'getInspectorSourceCodeBlock(');
  expectIncludes(index, '{ before: 1, after: 4, includeLineNumbers: true }');
  expectIncludes(index, 'const locationLine = sourceInfo.path ? `${shortPath}:${sourceInfo.line ?? 1}:${sourceInfo.column ?? 1}` :');
  expectIncludes(index, 'return `${codePreview}\\n\\n${locationLine}`;');
  expectNotIncludes(index, 'const match = raw.match(/^(.*?)(?::(\\d+))?(?::(\\d+))?$/);');
  expectNotIncludes(index, 'return `${sourceInfo.path}${line}${column}`;');
  expectNotIncludes(index, 'function parseInspectorSource(raw: string | null): InspectorSourceInfo');
  expectNotIncludes(index, 'function normalizeInspectorSourcePath(path: string)');
  expectNotIncludes(index, 'function getInspectorSourceCodePreview(sourceInfo: InspectorSourceInfo)');
  expectIncludes(index, '左侧栏区域（当前元素没有源码行预览）');
  expectIncludes(index, '已识别源码定位标记，暂无源码行预览');
  expectIncludes(index, '当前元素没有源码定位标记');
  expectNotIncludes(index, 'return code ? code.trim() : undefined;');
  expectIncludes(index, 'function getInspectorSourceCodePreviewFromElement(element: HTMLElement)');
  expectIncludes(index, 'function isUsefulInspectorCodePreview(code: string | undefined)');
  expectIncludes(index, 'const classNames = Array.from(element.classList);');
  expectIncludes(index, 'classMatches.every(className => line.includes(className))');
  expectIncludes(index, 'code: line.trim(),');
  expectIncludes(index, 'line: index + 1,');
  expectIncludes(index, "column: Math.max(1, line.indexOf(`<${element.tagName.toLowerCase()}`) + 1),");
  expectIncludes(index, 'const directCodePreview = getInspectorSourceCodeBlock(');
  expectIncludes(index, 'const elementCodePreview = getInspectorSourceCodePreviewFromElement(element);');
  expectIncludes(index, 'const codePreview = isUsefulInspectorCodePreview(directCodePreview)');
  expectIncludes(index, 'if (codePreview) {');
  expectIncludes(index, 'const labelContent = codePreview ?? resolveInspectorSourceHint(element, Boolean(sourceInfo.path));');
  expectIncludes(index, 'return `${tag}${id}${className}\\n${labelContent}`;');
  expectNotIncludes(index, 'return `${tag}${id}${className}  ${resolveInspectorSourceHint(element)}`;');
  expectIncludes(index, 'const labelTop = rect.top > 180 ? rect.top - 172 : Math.min(rect.bottom + 6, Math.max(6, iframeHeight - 172));');
  expectIncludes(index, 'top: `${Math.round(labelTop)}px`');
  expectIncludes(index, 'left: `${Math.round(labelLeft)}px`');
  expectIncludes(index, 'overlay.label.innerHTML = highlightInspectorCodeLabel(getInspectorElementLabel(target));');
  expectNotIncludes(index, 'overlay.label.textContent = getInspectorElementLabel(target);');
  expectIncludes(index, 'iframeDoc.elementFromPoint(event.clientX, event.clientY)');
  expectIncludes(index, 'target.getBoundingClientRect()');
  expectIncludes(index, 'function updateInspectorOverlay(iframeDoc: Document, overlay: InspectorOverlay, target: HTMLElement)');
  expectIncludes(index, 'updateInspectorOverlay(iframeDoc, overlay, target)');
  expectIncludes(index, "addEventListener('mouseleave', onMouseLeave, true)");
  expectIncludes(index, "removeEventListener('mouseleave', onMouseLeave, true)");
  expectIncludes(index, 'const iframeWidth = iframeDoc.defaultView?.innerWidth');
  expectNotIncludes(index, 'function syncInspectorElementFromTarget');
  expectNotIncludes(index, 'syncInspectorElementFromTarget(inspector, target);');
  expectNotIncludes(index, 'inspector?.trackCode?.();');
  expectIncludes(index, 'const sourceInfo = getInspectorSourceInfo(target);');
  expectIncludes(index, 'function buildSelectedElementPath(target: HTMLElement, sourceInfo: InspectorSourceInfo)');
  expectIncludes(index, 'function markSelectedTarget(iframeDoc: Document, target: HTMLElement, path: string, sourceInfo: InspectorSourceInfo)');
  expectIncludes(index, "target.setAttribute('data-preset-manager-selected-source', path)");
  expectIncludes(index, "target.setAttribute('data-preset-manager-dev-selected', 'true')");
  expectIncludes(index, "element.removeAttribute('data-preset-manager-dev-selected')");
  expectIncludes(index, 'data-preset-manager-dev-stable-id');
  expectIncludes(index, 'function buildSelectedElementSelectors');
  expectIncludes(index, 'function ensureStableElementId');
  expectIncludes(index, 'selectors: buildSelectedElementSelectors');
  expectIncludes(index, 'stability: sourceInfo.path ?');
  expectIncludes(index, 'const pathKey = buildSelectedElementPath(target, sourceInfo);');
  expectIncludes(index, 'const markedCount = markSelectedTarget(iframeDoc, target, pathKey, sourceInfo);');
  expectIncludes(index, 'if (!sourceInfo.path) {');
  expectIncludes(index, 'dispatchSelectFor(target);');
  expectIncludes(index, 'toastr.warning(\'这个元素已选中，可调样式；但暂时没有源码定位。\', \'\', { timeOut: 1800 });');
  expectIncludes(index, 'requestCodeInspectorLocate(iframeDoc, sourceInfo);');
  expectIncludes(index, 'console.info(\'[Preset Manager] code inspector locate\',');
  expectIncludes(index, 'if (!enabled) return;');
  expectIncludes(index, 'const target = findInspectableElement(iframeDoc, event);');
  expectIncludes(index, 'event.preventDefault();');
  expectIncludes(index, 'event.stopPropagation();');
  expectIncludes(index, 'event.stopImmediatePropagation();');
  const mouseMoveSource = index.slice(index.indexOf('const onMouseMove'), index.indexOf('const onMouseLeave'));
  expectNotIncludes(mouseMoveSource, 'dispatchSelectFor(target);');
  expectIncludes(index, 'if (!shouldToggleInspectorOnAltShift(event, state)) return;');
  expectIncludes(index, 'showCodeInspectorStateToast(setEnabled(!enabled));');
  expectIncludes(index, "defaultView?.addEventListener('keydown', onKeyDown, true)");
  expectIncludes(index, "defaultView?.removeEventListener('keydown', onKeyDown, true)");
  expectIncludes(index, "defaultView?.addEventListener('blur', onWindowBlur, true)");
  expectIncludes(index, 'resetAltShiftToggleState({ altKey: false, shiftKey: false }, state)');
  expectNotIncludes(index, 'activeInspector.trackCode?.();');
  expectNotIncludes(index, 'setEnabled(true)');
  expectNotIncludes(index, 'inspector.internalLocate = false;');
  expectIncludes(index, 'iframeDoc.createElement(\'img\')');
  expectIncludes(index, 'encodeURIComponent(file)');
  expectNotIncludes(index, 'encodeURIComponent(inspector.element.path)');
  expectIncludes(index, 'http://${ip}:${port}/?file=');
  expectNotIncludes(index, 'locate: false');
  expectNotIncludes(index, 'locate: true');
  expectNotIncludes(index, "import codeInspectorClient from './codeInspectorClient.generated.js';");
  expectIncludes(index, "from './utils/codeInspectorToggle'");
  expectNotIncludes(index, "createElement('script')");
  expectNotIncludes(index, 'codeInspectorClient.trim()');
  expectNotIncludes(index, "typeof __PRESET_MANAGER_CODE_INSPECTOR_CLIENT__ === 'string'");
  expectIncludes(webpackConfig, 'codeInspectorWebpackLoaderPath');
  expectIncludes(webpackConfig, 'start_preset_manager_code_inspector_server');
  expectIncludes(webpackConfig, 'startPresetManagerCodeInspectorServer');
  expectIncludes(webpackConfig, 'spawnCodeInspectorEditor');
  expectIncludes(webpackConfig, "const command = process.platform === 'win32' ? 'code.cmd' : 'code';");
  expectIncludes(webpackConfig, "const args = ['-g', `${file}:${line}:${column}`];");
  expectIncludes(webpackConfig, '[code_inspector]');
  expectIncludes(webpackConfig, ']\\x1b[0m open`, { command, args }');
  expectIncludes(webpackConfig, 'loader: codeInspectorWebpackLoaderPath');
  expectIncludes(webpackConfig, 'buildPresetManagerSourceLines');
  expectIncludes(webpackConfig, '__PRESET_MANAGER_SOURCE_LINES__');
  expectNotIncludes(webpackConfig, 'codeInspectorPlugin({ bundler: \'webpack\', editor: \'code\' })');
  expectNotIncludes(webpackConfig, 'codeInspectorClientIifePath');
  expectNotIncludes(webpackConfig, '__PRESET_MANAGER_CODE_INSPECTOR_CLIENT__');
  expectNotIncludes(webpackConfig, 'inject-loader.js');
  expectNotIncludes(webpackConfig, 'client.iife.js');
  expectNotIncludes(webpackConfig, "process.env.CODE_EDITOR = 'code.cmd';");

  console.info('codeInspectorIframe tests passed');
})();
